$(document).ready(function(){
 $(".img1").click(function(){
 $(".des").show();
 $(".img1").hide();
});
$(".des").click(function(){
  $(".img1").show();
  $(".des").hide();
 });
 $(".img2").click(function(){
  $(".dev").show();
  $(".img2").hide();
 });
 $(".dev").click(function(){
  $(".img2").show();
  $(".dev").hide();
 });
 $(".img3").click(function(){
  $(".prod").show();
  $(".img3").hide();
 });
 $(".prod").click(function(){
  $(".img3").show();
  $(".prod").hide();
 });
});